# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
weight = 2
name = "Projects"

[[main]]
weight = 3
name = "Remixes"

[[main]]
parent = "Projects"
name = "Otsi.mk2"
url = "/projects/Otsi.mk2/Otsi-info"
weight = 1
[[main]]
parent = "Projects"
name = "Hackathon2024"
url = "/projects/Hackyeah2024"
weight = 2

[[main]]
parent = "Remixes"
name = "CapibaraZero"
url = "/projects/CapibaraZero"

[[main]]
name = "About Us"
url = "/about"
weight = 4

[[main]]
name = "Contact Us"
url = "/contact"
weight = 5

# footer menu
#[[footer]]
#name = "About"
#url = "/about"
#weight = 1